version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo_home:/data/db

  # Flask app service
  flask-app:
    build:
      context: .
    ports:
      - "4000:5000"
    environment:
      MONGODB_ADDRESS: "mongodb://mongodb:27017/mydatabase"
      NTFY_BASE_URL: "https://ntfy:8070/"

  # ntfy server service
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Budapest    # optional: set desired timezone
    volumes:
      - ~/ntfy/data/cache:/var/cache/ntfy
      - ~/ntfy/data/etc:/etc/ntfy
    ports:
      - 8070:80
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:8070/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped